cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.remove_cart, name='remove_cart'),
	path('completly_remove/<int:product_id>/', views.completly_remove, name='completly_remove'),
] 

ketoworld/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signUpView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
]

# Mapping STATIC and Media URLS

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path 
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult')
]
 

shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail')
]

shop/models.py
from django.db import models
from django.urls import reverse


# Category Model


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    # Meta class
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    # Getting Category
    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])


    # Redering Function
    def __str__(self):
        return '{}'.format(self.name)


# Products Model

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    # Meta Class

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    # Getting Reverse Url for Product

    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])

    # Rendering Function

    def __str__(self):
        return '{}'.format(self.name)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=100, required=True)
	last_name = forms.CharField(max_length=100, required=True)
	email = forms.EmailField(max_length=254, help_text='eg. youremail@anyemail.com')

	class Meta:
		model = User
		fields = ('first_name','last_name','email','username','password1','password2')

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib.auth.models import Group, User
from .forms import SignUpForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout

# All views


def index(request):
    text_var = "Hi Im syed Ahmed"
    return HttpResponse(text_var)


# Category view

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    '''Pagination code'''
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop/category.html', {'category': c_page, 'products': products})


# Product View

def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html',  {'product': product})


# User signUp View

def signUpView(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            signup_user = User.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            # assigning signup to customer group
            customer_group.user_set.add(signup_user)
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


# User signin View

def signinView(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            # Checking if user returing a non-value or not
            if user is not None:
                login(request, user)
                return redirect('shop:allProdCat')
            else:
                return redirect('signup')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/signin.html', {'form': form})


# User logout view

def signoutView(request):
    logout(request)
    return redirect('signin')

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      name="description"
      content="{% block metadescription %} {% endblock %}"
    />
    <!-- Google Font -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
      rel="stylesheet"
    />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <div class="container-fluid bg-light navbar-fixed-top navbarTop">
        {% include 'top_navbar.html' %}
      </div>
      {% include 'header.html' %} 
      {% include 'navbar.html' %} 
      {% block content %} 
      {% endblock %}
    </div>
    {% include 'footer.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery JS -->
    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <!-- Popper JS -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- FontAwesome Kit JS -->
    <script src="{% static 'js/57a85e83d6.js' %}"></script>
  </body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
	<p class="text-center">&copy; Keto World. All Rights Reserved.</p>
</div>

shop/templates/header.html
{% load static %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="Keto World Store"></a>
	</center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li> 
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult'%}" method="GET">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>  
  </div> 
</nav>

shop/templates/top_navbar.html
<div class="container">
    <div class="navbarTopMenu">
        <ul>
            {% if request.user.is_authenticated and request.user.first_name %}
             <li>
                 Welcome, {{request.user.first_name}} <i class="fas fa-user-circle"></i>
             </li>
             <li>
                 <a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
             </li>
             {% else %}
             <li>
                 <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
             </li>
             <li>
                 <a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
             </li>
             {% endif %}
        </ul>
    </div>
</div>