cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
	path('add/<int:product_id>/', views.add_cart, name='add_cart'),
	path('', views.cart_detail, name='cart_detail'),
	path('remove/<int:product_id>/', views.remove_cart, name='remove_cart'),
	path('completly_remove/<int:product_id>/', views.completly_remove, name='completly_remove'),
] 

ketoworld/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('account/create/', views.signUpView, name='signup'),
    path('account/login/', views.signinView, name='signin'),
    path('account/logout/', views.signoutView, name='signout'),
]

# Mapping STATIC and Media URLS

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail')
]

cart/models.py
from django.db import models
from shop.models import Product


# Cart Model

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        db_table = 'ShoppingCart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


# Cart Item Model

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'ShppoingCartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
import stripe
from django.conf import settings
from order.models import Order, OrderItem
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage

# Session ID Checker function


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# Function to adding products to shopping cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

# Cart Deitails View


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_total = int(total * 100)
    description = 'Keto World Shop - New Order'
    data_key = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        # print(request.POST)
        try:
            token = request.POST['stripeToken']
            email = request.POST['stripeEmail']
            billingName = request.POST['stripeBillingName']
            billingAddress1 = request.POST['stripeBillingAddressLine1']
            billingcity = request.POST['stripeBillingAddressCity']
            billingPostcode = request.POST['stripeBillingAddressZip']
            billingCountry = request.POST['stripeBillingAddressCountryCode']
            shippingName = request.POST['stripeShippingName']
            shippingAddress1 = request.POST['stripeShippingAddressLine1']
            shippingcity = request.POST['stripeShippingAddressCity']
            shippingPostcode = request.POST['stripeShippingAddressZip']
            shippingCountry = request.POST['stripeShippingAddressCountryCode']
            customer = stripe.Customer.create(
                email=email,
                source=token
            )
            charge = stripe.Charge.create(
                amount=stripe_total,
                currency="eur",
                description=description,
                customer=customer.id
            )
            '''Creating the order'''
            try:
                order_details = Order.objects.create(
                    token=token,
                    total=total,
                    emailAddress=email,
                    billingName=billingName,
                    billingAddress1=billingAddress1,
                    billingCity=billingcity,
                    billingPostcode=billingPostcode,
                    billingCountry=billingCountry,
                    shippingName=shippingName,
                    shippingAddress1=shippingAddress1,
                    shippingCity=shippingcity,
                    shippingPostcode=shippingPostcode,
                    shippingCountry=shippingCountry
                )
                order_details.save()
                for order_item in cart_items:
                    oi = OrderItem.objects.create(
                        product=order_item.product.name,
                        quantity=order_item.quantity,
                        price=order_item.product.price,
                        order=order_details
                    )
                    oi.save()
                    '''Reduce stock when order is placed or saved'''
                    products = Product.objects.get(id=order_item.product.id)
                    products.stock = int(
                        order_item.product.stock - order_item.quantity)
                    products.save()
                    order_item.delete()
                    '''The terminal will print this message when the order is saved'''
                    print('The order has been created')
                try:
                    '''Calling the sendEmail function'''
                    sendEmail(order_details.id)
                    print('The order email has been sent to the customer.')
                except IOError as e:
                    return e
                return redirect('order:thanks', order_details.id)
            except ObjectDoesNotExist:
                pass
        except stripe.error.CardError as e:
            return False, e
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter, data_key=data_key, stripe_total=stripe_total, description=description))

# Removing single item from cart


def remove_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

# Completly removing all item from the cart


def completly_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

# Email test


def sendEmail(order_id):
    transaction = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=transaction)
    try:
        '''Sending the order'''
        subject = "Keto World Store - New Order #{}".format(
            transaction.id)
        to = ['{}'.format(transaction.emailAddress)]
        from_email = settings.EMAIL_HOST_USER
        order_information = {
            'transaction': transaction,
            'order_items':	order_items
        }
        message = get_template('email/email.html').render(order_information)
        msg = EmailMessage(subject, message, to=to, from_email=from_email)
        msg.content_subtype = "html"
        msg.send()
    except IOError as e:
        return e

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
	This is the shopping cart page. Proceed to review your items and place the order.
{% endblock %}
{% block title %}
	Cart - Keto World Store
{% endblock %}
{% block content %}
	{% if not cart_items %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center cart_title">
					Your shopping cart is empty
				</h1>
				<br>
				<p class="text-center">
					Please click <a href="{% url 'shop:allProdCat' %}" class="cart_a">here</a> to continue shopping.
				</p>
			</div>
		</div>
	{% else %}
		<div>
			<div class="text-center">
				<br>
				<h1 class="text-center cart_title">
					Your shopping cart
				</h1>
				<br>
			</div>
		</div>
		<div class="row mx-auto">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table cart_table">
					<thead class="cart_thead">
						<tr>
							<th colspan="5">
								Your items
							</th>
						</tr>
						
					</thead>
					<tbody>
						{% for cart_item in cart_items %}
							<tr>
								<td>
									<a href="{{cart_item.product.get_url}}"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded cart_img"></a>
								</td>
								<td class="text-left">
									{{cart_item.product.name}}
									<br>
									SKU: {{cart_item.product.id}}
									<br>
									Unit Price: £{{cart_item.product.price}}
									<br>
									Qty: {{cart_item.quantity}} x £{{cart_item.product.price}}
								</td>
								<td>
									£{{cart_item.sub_total}}
								</td>
								{% if cart_item.quantity < cart_item.product.stock %}
									<td>
										<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="cart_a"><i class="fas fa-plus-circle cart_icon"></i></a>&nbsp;<a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="cart_a"><i class="fas fa-minus-circle cart_icon"></i></a>&nbsp;<a href="{% url 'cart:completly_remove' cart_item.product.id %}" class="cart_icon"><i class="fas fa-trash-alt cart_icon"></i></a>
									</td>
								{% else %} 
									<td>
										&nbsp;<a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="cart_a"><i class="fas fa-minus-circle cart_icon"></i></a>&nbsp;<a href="{% url 'cart:completly_remove' cart_item.product.id %}" class="cart_icon"><i class="fas fa-trash-alt cart_icon"></i></a>
									</td>
									<td></td>
								{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
				<table class="table cart_table">
					<thead class="cart_thead">
						<tr>
							<th>
								Checkout
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>
								Please review your shopping cart items before proceeding with the order payment.
							</td>
						</tr>
						<tr>
							<td class="text-left">
								Your total is: <strong>£{{ total }}</strong>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="mx-auto">
					<form action="" method="POST">
						{% csrf_token %}
					  <script
					    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
					    data-key="{{ data_key }}"
					    data-amount="{{ stripe_total }}"
					    data-name="Keto World Store"
					    data-description="{{ description }}"
					    data-image="{% static 'img/logo.png' %}"
					    data-locale="auto"
					    data-currency="eur"
					    data-shipping-address="true"
					    data-billing-address="true"
					    data-zip-code="true">
					  </script>
					</form>
					<a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block btnD1">Continue Shopping</a> 
				</div>
			</div>
		</div>
		<br>
	{% endif %}
{% endblock %}